spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

# Logging Configuration
logging:
  level:
    root: INFO                   # Set the root logging level
    org.springframework: INFO      # Set the logging level for Spring framework classes
    org.hibernate: INFO           # Set the logging level for Hibernate
    your.package.name: DEBUG      # Set the logging level for your specific package (customize as needed)
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'  # Customize console log format
  file:
    name: logs/demo-application.log  # Log file name
    max-size: 10MB                   # Max size of the log file before rotation
    max-history: 30                   # Keep the last 30 log files